# Generated by Django 4.1.5 on 2023-01-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dislike',
        ),
    ]
