# Generated by Django 4.1.5 on 2023-01-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_delete_dislike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='like',
            old_name='like',
            new_name='count',
        ),
    ]
